### ISSUE TITLE
Cannot add transaction in offline mode (forever spinning circle)

### ISSUE THREAD

**Issue by mehuser** [emansih/FireflyMobile#157] opened 2021-03-13 18:20 UTC
**Firefly III Server Version:**
5.5.0-beta.1 (also tested with 5.4.6)

**Firefly III Mobile Version:**
4.3.0 - Fdroid

**Android Version:**  
Android 11 - GrapheneOS

**Device Information:**  

- BRAND: google
- MODEL: Pixel4a
--------------------------------------

## Expected Behavior
In offline mode, when I add a transaction, I expect to receive message the message "Transaction will be added when you are back online".
## Current Behavior
Forever spinning circle, must force back to return to dashboard. Transaction is not added.
## Steps to Reproduce
1. Open the application
2. switch the airplane toggle to reproduce Firefly server unreachability
3. add a transaction from dashboard

## Notes
Adding categories, account and other items while offline does work. Only adding transaction fails.

## Screen 
![Screenshot_20210313-191346](https://user-images.githubusercontent.com/485878/111039882-ba127300-8430-11eb-8ed9-86b7e6be6311.png)

**Comment by emansih** [comment] 2021-03-13 23:58
Hi. I am closing this issue because it is a duplicate of #155 . I have provided an APK https://github.com/emansih/FireflyMobile/issues/155#issuecomment-798804162 for you to try. It should crash and show you the stack trace.

**Closed by emansih** 2021-03-13 23:58 UTC
